version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    depends_on: 
      - kafka
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
  kafka-manager:
    image: sheepkiller/kafka-manager
    depends_on: 
      - kafka
    environment:
      ZK_HOSTS: 'zookeeper:2181'
    ports:
      - '9000:9000'
  app:
    build: ./
    depends_on: 
      - zookeeper
