name: Release Example Artifacts

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tar all examples
        working-directory: ./examples
        run: for i in */; do tar -zcvf "${i%/}.tar.gz" "$i"; done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            examples/startup.sh
            examples/*.tar.gz
            LICENSE
